name: Schedule
on:
  workflow_dispatch: {}    # 手動実行を許可
  schedule:                # 定期実行イベント
    - cron: '*/5 * * * *'  # 5分ごとに起動(scheduleイベントの最小単位は5分)
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: date